### ISSUE TITLE
GPS tracking for Android August 27th

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/Android-Sitter-Mobile#17]
I did a quick GPS test in-between rain storms. I will have to wait for a bit to try again.

The route is way off.

![image](https://user-images.githubusercontent.com/41838025/44692292-e0fe2a80-aa27-11e8-9afc-a7999d1772fd.png)

**Comment by teddyhoo** [comment]
https://eng.uber.com/rethinking-gps/ 
and this one
http://gpsworld.com/how-to-achieve-1-meter-accuracy-in-android/

This is a good article on GPS issues. I didn't know Android had a raw data API of satellite data. Since I don't think you are in an urban area, the satellite positioning issues may not apply. I put the articles in there mostly for me, but if you want to get feel for the underlying issues, knock yourself out. 

There are some basic things we should check on your device:

1. Make sure High Accuracy turned on in Location settings
2. Check your Battery saving mode: if it Power Save, turn that off
3. Download this app GPS Status & Toolbox by MobiWIA and reset the GPS (clear out stuff)
4. Check Bluetooth settngs; turn on, this helps

Also, see if this occurs on regular basis for the same coordinates, noting where you have the device (pocket, is there a cigarette case made of tin that in the pocket too that would obstruct signal). The segment where you appear to not have collected points looks like background mode. 8 is much stricter but it should be mitigated by the Notification thing which signals to the OS that we are in the foregroudn and should not be limited to background rules. Make sure the foreground notification is coming up when you push into background. 

I will attach the GPS I did this AM. My GPS tracking is on a device that does not have phone plan. It is in dense urban area but with no skyscraper obstructions. If some of your routes are accurate and some parts of inaccurate routes are accurate, this would tend to indicate there is some environmental issue at play.

**Comment by teddyhoo** [comment]
<img width="585" alt="screen shot 2018-08-27 at 9 05 37 pm" src="https://user-images.githubusercontent.com/5602683/44694742-56282a80-aa3d-11e8-934c-ed762651122f.png">

**Comment by jodsmithLT** [comment]
Second walk awhile later is better, but still GPS track is a little shaky.

![image](https://user-images.githubusercontent.com/41838025/44694754-0c3b4680-aa35-11e8-9ca6-ac663300f68b.png)

Phone is in my pocket the whole time, except when I took the picture.

Location set for High Accuracy.  
Battery is at 92% - Battery Saving Mode is OFF
Bluetooth is turned on.

Will try downloading the GPS Status & Toolbox by MobiWIA tomorrow

**Comment by teddyhoo** [comment]
Try to see if you determine the physical position of the device while walking / moving. I want unobstructed baseline. Download that app because it will offer some good diagnostic info.

**Comment by teddyhoo** [comment]
<img width="1440" alt="screen shot 2018-08-28 at 1 53 03 pm" src="https://user-images.githubusercontent.com/5602683/44741692-d9905d00-aacb-11e8-8543-e5786a443dd5.png">

**Comment by teddyhoo** [comment]
I ran a test and marked visit arrive last night and then marked complete this am. It tracked accurately with no extraneous points. I did not subsequently mark arrive on new visit in future day (before I intentionally crashed the app).

**Comment by teddyhoo** [comment]
<img width="823" alt="screen shot 2018-09-09 at 8 33 21 pm" src="https://user-images.githubusercontent.com/5602683/45270945-b3c26b00-b470-11e8-8e29-91bdc460f173.png">

**Comment by teddyhoo** [comment]
<img width="823" alt="screen shot 2018-09-09 at 8 33 21 pm" src="https://user-images.githubusercontent.com/5602683/45270956-cd63b280-b470-11e8-9b0f-25159140d5c7.png">

**Comment by teddyhoo** [comment]
<img width="600" alt="screen shot 2018-09-09 at 8 27 17 pm" src="https://user-images.githubusercontent.com/5602683/45270957-d5bbed80-b470-11e8-9656-b52630c764a2.png">

**Comment by teddyhoo** [comment]
Ran 2 side-by-side routes on Android and IOS simultaneously for similar walk terrain. Above maps show routes walked.

**Comment by jodsmithLT** [comment]
Ted,
Can you tell me what GPS Status & Toolbox by MobiWIA will tell me? I downloaded it on my Android and not sure what to do with it.

Fresh GPS test today. Both apps in my pockets. - the iPhone walk was pretty much the exact track I walked. The Android still seems a little spastic. 

iPhone:
![image](https://user-images.githubusercontent.com/41838025/45305075-2833f300-b4df-11e8-80b2-5f4258d1f98c.png)

Android:
![image](https://user-images.githubusercontent.com/41838025/45305105-35e97880-b4df-11e8-8958-5daf7571c005.png)
